### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by frozencemetery** [DirectXMan12/should_be#2]
```
(.venv) (0) rharwood@seton:/tmp$ pip install shouldbe
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting shouldbe
  Using cached https://files.pythonhosted.org/packages/89/bf/8a52bdb657f4aa160325e594ea1ffbe2e84eda7f50f13db35a9ff21bd7b6/shouldbe-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-P84HGo/shouldbe/setup.py", line 11, in <module>
        long_description=open('README.txt').read(),
    IOError: [Errno 2] No such file or directory: 'README.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-P84HGo/shouldbe/
(.venv) {1} (1) rharwood@seton:/tmp$ 
```

**Comment by DirectXMan12** [comment]
fixed in 0.1.2.  setuptools started traversing symlinks and also appears to stop bundling README.txt when it can bundle README.rst.
